service: serverless-store

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-2
  memorySize: 128
  timeout: 30

functions:
  products:
    handler: functions/products.handler
    event:
      - http: GET products
      - http: PUT cart
      - http: OPTIONS cart
      - http: POST checkout
      - http: OPTIONS checkout
    users:
      handlers: functions/users.handler
      events:
        - http: GET users
        - http: POST users
        - http: PUT users
        - http: DELETE users
        - http: OPTIONS users