service: serverless-store

custom:
  cognitoAuthorizer: arn:aws:cognito-idp:ap-northeast-2:778740201320:userpool/ap-northeast-2_cu1JdcyH6

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Scan"
        - "dynamodb:Query"
        - "dynamodb:OutItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:BatchWriteItem"
      Resource: [
        "arn:aws:dynamodb:ap-northeast-2:*:table/Product",
      ]
  stage: dev
  region: ap-northeast-2
  memorySize: 128
  timeout: 30

functions:
  products:
    handler: functions/products.handler
    events:
      - http: GET products
      - http:
          method: GET
          path: productsAuth
          authorizer:
            arn: ${self:custom.cognitoAuthorizer}
      - http: OPTIONS productsAuth
      - http: PUT cart
      - http: OPTIONS cart
      - http: POST checkout
      - http: OPTIONS checkout
  users:
    handler: functions/users.handler
    events:
      - http: GET users
      - http: POST users
      - http: PUT users
      - http: DELETE users
      - http: OPTIONS users